### ISSUE TITLE
Simularium Engine doesn't build with GCC 11

### ISSUE THREAD

**Issue by EricJIsaac** [allen-cell-animated/simularium-engine#15]
## Description

The aws-sdk-cpp dependency fails to build with GCC 11, blocking local native builds on 'up-to-date' Linux distributions

## Expected Behavior

A successful build with GCC 11

## Reproduction

Attempt to build the project with GCC 11.x

## Solution

Update the AWS SDK CPP, to receive relevant fixes needed to build w/ GCC 11

**Comment by toloudis** [comment]
Is this related? 
https://github.com/aws/aws-sdk-cpp/issues/1635

**Comment by EricJIsaac** [comment]
Yes, 

> Is this related/relevant?
> [aws/aws-sdk-cpp#1635](https://github.com/aws/aws-sdk-cpp/issues/1635)

Yes, this is one of the (now resolved) issues. The fix they suggested didn't work in our case, but I was able to find a work-around between another similar issue and the gcc manual (additional flags, aws-sdk-build config, and disabling the auto-run tests).

Some others include:
https://github.com/aws/aws-sdk-cpp/issues/1697 (resolved)
https://github.com/sakra/cotire/issues/87 (not exactly, but similar)
