### ISSUE TITLE
DNS lambda failed to update Dev

### ISSUE THREAD

**Issue by blairlyons** [allen-cell-animated/simularium-engine#28]
## Description

_A clear description of the bug_

## Expected Behavior

_What did you expect to happen instead?_

## Reproduction

_A minimal example that exhibits the behavior._

## Environment

_Any additional information about your environment. E.g. OS version, python version, browser etc._

**Comment by EricJIsaac** [comment]
Has not been observed again, can file a more specific bug if it does
