### ISSUE TITLE
Ensure that staging and production truly go to different back-end servers

### ISSUE THREAD

**Issue by blairlyons** [allen-cell-animated/simularium-engine#29]
## What needs to happen?
Confirm whether staging and production front ends are truly connecting to different staging and production back-ends.  (At this time, I suppose this is a matter of checking the backend URL that the front end tries to connect to, in both staging and prod. And if they are different, make sure they truly resolve to different machines )

If this is not the case, then we need to examine deployment to ensure that we create separate staging from production clusters, or at least have separate staging and production servers within the cluster (not sure if that second option is sufficiently robust).

## Why should we do this?
If the staging back end goes down it should not affect production, and vice versa.

## When does this need to get done?
Summer 2021

**Comment by EricJIsaac** [comment]
Verified
